adjust mobility model
fabianh001/the-one pull request #4
Opened 2021-12-05 13:51 UTC by sven0311

nodes are staying for 5 min in the same state
nodes are not doing rwp in the most areas
nodes are moving to the ubahn after exit state and are deactivated then

2021-12-05 16:18 UTC, geitner-max requested changes
Beim Durchlaufen habe ich folgende Nullpointerexception erhalten:
Exception in thread "main" java.lang.NullPointerException
	at movement.StatefulRwp.updateState(StatefulRwp.java:225)
	at movement.StatefulRwp.getPath(StatefulRwp.java:47)
	at core.DTNHost.setNextWaypoint(DTNHost.java:418)
	at core.DTNHost.move(DTNHost.java:396)
	at core.World.moveHosts(World.java:214)
	at core.World.update(World.java:164)
	at gui.DTNSimGUI.runSim(DTNSimGUI.java:113)
	at ui.DTNSimUI.start(DTNSimUI.java:77)
	at core.DTNSim.main(DTNSim.java:92)

Da fehlt irgendwo noch eine state==null Abfrage.

2021-12-05 16:22 UTC, sven0311 commented
@geitner-max du hast glaub ich nicht den neusten Stand. Das sollte behoben sein

2021-12-05 16:24 UTC, geitner-max approved these changes

2021-12-05 16:24 UTC, geitner-max commented
Stimmt, da gab es noch einen neuen Commit. Jetzt geht alles. Passt!

2021-12-06 09:21 UTC, fabianh001 approved these changes

2021-12-06 09:21 UTC, merged